<?php
/**
 * @file
 * amv_blitz_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function amv_blitz_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'Rules & Submission Guidelines',
  'log' => '',
  'status' => '1',
  'comment' => '0',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '7f7bf0b7-b808-46ef-9bb3-51762f1c14ba',
  'ds_switch' => '',
  'type' => 'page',
  'language' => 'und',
  'created' => '1364793526',
  'tnid' => '0',
  'translate' => '0',
  'rh_action' => '-1',
  'rh_redirect' => '',
  'rh_redirect_response' => '301',
  'uuid' => '68ce794a-fa03-4ac1-bd57-16a45e7f885f',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Version 1.0</p>

<p>Unlike the standard AMV competition, there are no themes/genres. This means that to enter this tournament, you can make any short AMVs you want in any genre you like! As long as it is something that you make that would interest the judges, then you be on your way to tournament! If you do succeed in the qualifying round, then themes will be provided to you and your opponent in that round. As you progress, the themes you encounter will become difficult. The winner of the tournament will be the one who goes through all the rounds and wins the Grand Final!</p>

<p>Contents:</p>
<ul>
<li><a href="#bookmark-tech">Technical Specifications</a></li>
<li><a href="#bookmark-timeline">Timeline and Competition Dates</a></li>
<li><a href="#bookmark-submission">Submission of Videos</a></li>
<li><a href="#bookmark-rules">Rules</a></li>
</ul>

<h2 id="bookmark-tech">Technical Specifications</h2>
<p>Blitz AMVs submitted must conform to the following technical specifications:</p>

<ul>
<li>Video resolution must be at 640 x 368 pixels (minimum) or larger</li>
<li>The following video formats and codecs are allowed:
<ul>
<li>.avi = DivX, XviD, Lagarith, HuffYUV</li>
<li>.mp4 = h.264, MPEG-4</li>
<li>.mov = MPEG-4, h.264</li>
<li>.wmv = WMV9</li>
</ul></li></ul>

<p>If there are any formats and/or codecs that you wish to use that are not listed above, please contact the AMV co-ordinator first before you submit your AMV.</p>

<h2 id="bookmark-timeline">Timeline and Competition Dates</h2>
<p>Unlike the standard AMV competition, there are certain dates over the next few months which must be paid attention to. If you do enter, we will always update you on developments and the next dates you will know, depending on your status in the competition. The general overview of the Blitz Tournament timeline is as follows:</p>

<h3>General acceptance period:</h3>
<ul>
<li>April 2: Start of BAMV, accepting entries from EVERYONE.</li>
<li>April 30: Deadline for the acceptance period.</li>
<li>May 1: Start of judging of all the entries.</li>
<li>May 13: Judging of all entries end. Top 16 chosen.</li>
</ul>

<h3>Preliminary Final Period (Round of 16 – 16 entrants left):</h3>
<ul>
<li>May 14: Top 16 announced to the public. Start of the Preliminary Finals. Matches and themes are drawn. Accepting entries from the Top 16 entrants.</li>
<li>May 28: Deadline for entries in the Preliminary Finals.</li>
<li>May 29: Start of judging of the Preliminary Finals.</li>
<li>June 3: Judging of Preliminary Finals entries end. Top 8 chosen.</li>
</ul>

<h3>Quarter Final Period (8 entrants left):</h3>
<ul>
<li>June 4: Preliminary Finals winners announced to the public. Start of the Quarter Finals. Matches and themes are drawn. Accepting entries from the Top 8 entrants.</li>
<li>June 18: Deadline for entries in the Quarter Finals.</li>
<li>June 19: Start of judging of the Quarter Finals.</li>
<li>June 24: Judging of the Quarter Finals entries end. Top 4 chosen.</li>
</ul>

<h3>Semi Final Period (4 entrants left):</h3>
<ul>
<li>June 25: Quarter Finals winners announced to the public. Start of the Semi Finals. Matches and themes are drawn. Accepting entries from the Top 4 entrants.</li>
<li>July 9: Deadline for entries in the Semi Finals.</li>
<li>July 10: Start of judging of the Semi Finals.</li>
<li>July 15: Judging of the Semi Finals entries end. Top 2 chosen.</li>
</ul>

<h3>Grand Final Period (2 entrants left)</h3>
<ul>
<li>July 16: Semi Finals winners announced to the public. Start of the Grand Final. The theme is drawn. Accepting entries from the last 2 entrants.</li>
<li>July 30: Deadline for entries in the Grand Final.</li>
<li>July 31: Start of judging of the Grand Final.</li>
<li>August 9: Judging of the Grand Final ends. Winner and Runner-up determined.</li>
</ul>

<h3>SMASH! Event Day</h3>
<ul>
<li>August 10: Winner and Runner-up of the SMASH! Blitz AMV tournament is announced on stage on the day!</li>
</ul>

<h2 id="bookmark-submission">Submission of videos</h2>
<p>
All AMVs will be submitted online. To enter into the tournament, please use our form here (<a href="/content/round-one">insert link here</a>) and enter your relevant details. You can upload your AMV at any file sharing site and provide us the link through your online form. We recommend the following file sharing sites:
</p>

<ul>
<li>Sendspace</li>
<li>Mediafire</li>
<li>Uploading.com</li>
</ul>

<p>The files uploaded should be <strong>no more than 300MB. YOUTUBE AND OTHER VIDEO SHARING LINKS WILL NOT BE ACCEPTED!</strong></p>

<p>Those who progress through the rounds, you will get a link to the submission form for that round via e-mail.</p>

<h2 id="bookmark-rules">Competition Rules</h2>
<ol>
<li>This competition is open to all Australians and Internationally! If you do make the Grand Final, you do not have to be at the event. Prizes will be mailed out.</li>
<li>To enter into this competition, you may only enter <strong>ONE</strong> video, and <strong>ONE</strong> video only in every period of the tournament.</li>
<li>In all periods of the tournament, including the General Acceptance Period, your video shall be <strong>no shorter than 30 seconds and no longer than 1 minute 30 seconds.</strong></li>
<li>The purpose of this tournament is to showcase your talents and skill when making short AMVs. As such, we encourage you to make awesome and wonderful AMVs for this tournament and as a result, <strong>you may not submit any previous works of yours.</strong> This is to make sure we can keep the content in the tournament fresh, as well as you having the benefit of a challenge.</li>
<li>If you do enter this tournament and make it to the Preliminary final, your works will be available for download (uploaded on a file sharing site and links placed via our SMASH! forums) so that the general public can view them. This will also apply onwards from the Preliminary Final, regardless if you win or lose. If you wish to not have your works uploaded and available to the public by us, please send an email to us and we will not publish them.</li>
<li>In addition, we kindly ask that you <strong>do not release your work to the public (such as YouTube, AMV.org or any other video sharing sites) until after the results are announced in each period.</strong></li>
<li>Any video and audio material that is higher than a PG rating can be used, provided it is not used in an excessive way. Failure to follow this will result your AMV entry being disqualified.</li>
<li>Use of fansubs is <strong>STRICTLY PROHIBITED</strong>. No exceptions.</li>
<li>The AMV Co-ordinator and fellow staff have the <strong>final say</strong> on decisions made during the course of the competition, and therefore, cannot be disputed. If you have any other questions or enquiries regarding the Blitz AMV tournament, please do not hesitate to contact the AMV co-ordinator through email. </li>
</ol>',
        'summary' => '',
        'format' => 'html',
        'safe_value' => '<p>Version 1.0</p>

<p>Unlike the standard AMV competition, there are no themes/genres. This means that to enter this tournament, you can make any short AMVs you want in any genre you like! As long as it is something that you make that would interest the judges, then you be on your way to tournament! If you do succeed in the qualifying round, then themes will be provided to you and your opponent in that round. As you progress, the themes you encounter will become difficult. The winner of the tournament will be the one who goes through all the rounds and wins the Grand Final!</p>

<p>Contents:</p>
<ul><li><a href="#bookmark-tech">Technical Specifications</a></li>
<li><a href="#bookmark-timeline">Timeline and Competition Dates</a></li>
<li><a href="#bookmark-submission">Submission of Videos</a></li>
<li><a href="#bookmark-rules">Rules</a></li>
</ul><h2 id="bookmark-tech">Technical Specifications</h2>
<p>Blitz AMVs submitted must conform to the following technical specifications:</p>

<ul><li>Video resolution must be at 640 x 368 pixels (minimum) or larger</li>
<li>The following video formats and codecs are allowed:
<ul><li>.avi = DivX, XviD, Lagarith, HuffYUV</li>
<li>.mp4 = h.264, MPEG-4</li>
<li>.mov = MPEG-4, h.264</li>
<li>.wmv = WMV9</li>
</ul></li></ul><p>If there are any formats and/or codecs that you wish to use that are not listed above, please contact the AMV co-ordinator first before you submit your AMV.</p>

<h2 id="bookmark-timeline">Timeline and Competition Dates</h2>
<p>Unlike the standard AMV competition, there are certain dates over the next few months which must be paid attention to. If you do enter, we will always update you on developments and the next dates you will know, depending on your status in the competition. The general overview of the Blitz Tournament timeline is as follows:</p>

<h3>General acceptance period:</h3>
<ul><li>April 2: Start of BAMV, accepting entries from EVERYONE.</li>
<li>April 30: Deadline for the acceptance period.</li>
<li>May 1: Start of judging of all the entries.</li>
<li>May 13: Judging of all entries end. Top 16 chosen.</li>
</ul><h3>Preliminary Final Period (Round of 16 – 16 entrants left):</h3>
<ul><li>May 14: Top 16 announced to the public. Start of the Preliminary Finals. Matches and themes are drawn. Accepting entries from the Top 16 entrants.</li>
<li>May 28: Deadline for entries in the Preliminary Finals.</li>
<li>May 29: Start of judging of the Preliminary Finals.</li>
<li>June 3: Judging of Preliminary Finals entries end. Top 8 chosen.</li>
</ul><h3>Quarter Final Period (8 entrants left):</h3>
<ul><li>June 4: Preliminary Finals winners announced to the public. Start of the Quarter Finals. Matches and themes are drawn. Accepting entries from the Top 8 entrants.</li>
<li>June 18: Deadline for entries in the Quarter Finals.</li>
<li>June 19: Start of judging of the Quarter Finals.</li>
<li>June 24: Judging of the Quarter Finals entries end. Top 4 chosen.</li>
</ul><h3>Semi Final Period (4 entrants left):</h3>
<ul><li>June 25: Quarter Finals winners announced to the public. Start of the Semi Finals. Matches and themes are drawn. Accepting entries from the Top 4 entrants.</li>
<li>July 9: Deadline for entries in the Semi Finals.</li>
<li>July 10: Start of judging of the Semi Finals.</li>
<li>July 15: Judging of the Semi Finals entries end. Top 2 chosen.</li>
</ul><h3>Grand Final Period (2 entrants left)</h3>
<ul><li>July 16: Semi Finals winners announced to the public. Start of the Grand Final. The theme is drawn. Accepting entries from the last 2 entrants.</li>
<li>July 30: Deadline for entries in the Grand Final.</li>
<li>July 31: Start of judging of the Grand Final.</li>
<li>August 9: Judging of the Grand Final ends. Winner and Runner-up determined.</li>
</ul><h3>SMASH! Event Day</h3>
<ul><li>August 10: Winner and Runner-up of the SMASH! Blitz AMV tournament is announced on stage on the day!</li>
</ul><h2 id="bookmark-submission">Submission of videos</h2>
<p>
All AMVs will be submitted online. To enter into the tournament, please use our form here (<a href="/content/round-one">insert link here</a>) and enter your relevant details. You can upload your AMV at any file sharing site and provide us the link through your online form. We recommend the following file sharing sites:
</p>

<ul><li>Sendspace</li>
<li>Mediafire</li>
<li>Uploading.com</li>
</ul><p>The files uploaded should be <strong>no more than 300MB. YOUTUBE AND OTHER VIDEO SHARING LINKS WILL NOT BE ACCEPTED!</strong></p>

<p>Those who progress through the rounds, you will get a link to the submission form for that round via e-mail.</p>

<h2 id="bookmark-rules">Competition Rules</h2>
<ol><li>This competition is open to all Australians and Internationally! If you do make the Grand Final, you do not have to be at the event. Prizes will be mailed out.</li>
<li>To enter into this competition, you may only enter <strong>ONE</strong> video, and <strong>ONE</strong> video only in every period of the tournament.</li>
<li>In all periods of the tournament, including the General Acceptance Period, your video shall be <strong>no shorter than 30 seconds and no longer than 1 minute 30 seconds.</strong></li>
<li>The purpose of this tournament is to showcase your talents and skill when making short AMVs. As such, we encourage you to make awesome and wonderful AMVs for this tournament and as a result, <strong>you may not submit any previous works of yours.</strong> This is to make sure we can keep the content in the tournament fresh, as well as you having the benefit of a challenge.</li>
<li>If you do enter this tournament and make it to the Preliminary final, your works will be available for download (uploaded on a file sharing site and links placed via our SMASH! forums) so that the general public can view them. This will also apply onwards from the Preliminary Final, regardless if you win or lose. If you wish to not have your works uploaded and available to the public by us, please send an email to us and we will not publish them.</li>
<li>In addition, we kindly ask that you <strong>do not release your work to the public (such as YouTube, AMV.org or any other video sharing sites) until after the results are announced in each period.</strong></li>
<li>Any video and audio material that is higher than a PG rating can be used, provided it is not used in an excessive way. Failure to follow this will result your AMV entry being disqualified.</li>
<li>Use of fansubs is <strong>STRICTLY PROHIBITED</strong>. No exceptions.</li>
<li>The AMV Co-ordinator and fellow staff have the <strong>final say</strong> on decisions made during the course of the competition, and therefore, cannot be disputed. If you have any other questions or enquiries regarding the Blitz AMV tournament, please do not hesitate to contact the AMV co-ordinator through email. </li>
</ol>',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => 'it-admin',
  'picture' => '0',
  'data' => 'b:0;',
  'date' => '2013-04-01 16:18:46 +1100',
);
  return $nodes;
}
